TRAIN:
  ENABLE: True
  DATASET: EPICMASKOPT
  BATCH_SIZE: 16 # modified from 64
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_TYPE: caffe2
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1875  # ****modified from 0.1  0.0375
  LR_POLICY: cosine
  MAX_EPOCH: 120 # modified
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 2.0 # modified from 4.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 2  # modified
  ARCH: i3d
  # MODEL_NAME: 
  LOSS_FUNC:  cross_entropy  # modified from cross_entropy
  DROPOUT_RATE: 0.5     # modified from 0.5
TEST:
  ENABLE: True
  DATASET: EPICMASKOPT
  BATCH_SIZE: 16
  CHECKPOINT_TYPE: caffe2
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 4 # modified from 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .

G: generator
D: discriminator
DE: decoder
EN: encoder